### ISSUE TITLE
fail to resolve package for Windows

### ISSUE THREAD

**Issue by zheeeng** [lightyen/typescript-paths#4]

**Comment by lightyen** [comment]
I need more information.

**Comment by zheeeng** [comment]
After debugging this issue in Windows OS, I found that the resolver is fed with file paths with double backslashes, and the importer is slash style path.

https://github.com/lightyen/typescript-paths/blob/main/packages/typescript-paths/src/handler.ts#L109-L113

e.g.

filenames: [
    'D:\\foo\\bar.ts'
]

importer: 'D:/foo/bar.ts'

**Comment by lightyen** [comment]
Please use [path.normalize](https://nodejs.org/api/path.html#pathnormalizepath) before you call the handler.

**Comment by zheeeng** [comment]
Where can I normalize the file paths? I can't access the internal process.

**Comment by zheeeng** [comment]
@lightyen Please let me know if you need any additional information?

**Comment by lightyen** [comment]
I have tried on Windows and found nothing, may you describe more details or provide a reproduction about this problem?
