### ISSUE TITLE
[rollup-plugin-tsconfig-paths] Rollup 4 support

### ISSUE THREAD

**Issue by mrazauskas** [lightyen/typescript-paths#8]
Currently the `rollup-plugin-tsconfig-paths` declares:

https://github.com/lightyen/typescript-paths/blob/2a353f2bf3428b9d49a036fcb96b8844b28f0b21/packages/rollup-plugin-tsconfig-paths/package.json#L35-L37

Would it be possible to add Rollup 4 support, please?

**Comment by lightyen** [comment]
Fixed in v1.5.2

**Comment by mrazauskas** [comment]
Works as expected. Thanks for quick response!
