### ISSUE TITLE
Example config using @rollup/plugin-typescript

### ISSUE THREAD

**Issue by charlesritchea** [lightyen/typescript-paths#9]
Maybe I'm missing something everybody else knows, but why does the example rollup config not use @rollup/plugin-typescript?
I'm trying to replace ttypescript with this plugin, but using this plugin doesn't appear to do anything

**Comment by charlesritchea** [comment]
Are you pre-processing with tsc before rollup?

**Comment by lightyen** [comment]
> Are you pre-processing with tsc before rollup?

**No.** I just transpile typescript code to js with transpiler.(like `swc`, `esbuild` or `babel`)
